services:
  - type: web
    name: pqc-document-auth
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pqc-db
          property: connectionString
    
databases:
  - name: pqc-db
    databaseName: pqc_signatures
    user: pqc_user
